### ISSUE TITLE
您好，可以向您请教一下 elasticsearch-migration的问题吗？

### ISSUE THREAD

**Issue by taoyantu** [elasticsearch-cn/conference-site#15]
打扰您一下，想问一下 目前我使用您的程序 elasticsearch-migration，对导出的数据导入到另外一个elasticsearch 的时候，
命令如下
./esm -d http://192.168.92.128:9200 -y "tynum2"   -i=/ELK/snapshotbak/tomcawenjian

总是数据导入不全，tomcawenjian 文件，一共有1,683,651  条数据，可是只导入了185171条，想问一下，这个是什么问题？
Read 180005 / 185171 [===============================================================================================================================>---]  97.21% 0
Read 185171 / 185171 [===================================================================================================================================] 100.00% 0
Bulk 0 / 185171 [------------------------------------------------------------------------------------------------------------------------------------------]   0.00%

```
非常感谢您，能帮忙指点一下。谢谢
```

**Comment by medcl** [comment]
问错地方了吧，试试最新的版本
